#!/bin/bash

readonly SCRIPT_NAME=${0##*/}
readonly VERSION=1.0.0

print_help()
{
    cat << END
Test version
END
}

print_version()
{
    cat << END
$SCRIPT_NAME version $VERSION
END
}

print_error()
{
    cat << END 1>&2
$SCRIPT_NAME: $1
Try -h option for more information
END
}

# いつか元に戻す
#if [[ $# -eq 0 ]]; then
#    print_help
#    exit 0
#fi

OUTPUT_DIR="./SSERAFIM"

while getopts :o:hV option
do
    case "$option" in
        o)
            OUTPUT_DIR=$OPTARG
            ;;
        h)
            print_help
            exit 0
            ;;
        V)
            print_version
            exit 0
            ;;
        :)
            print_error "option requires an argument -- '$OPTARG'"
            exit 1
            ;;
        \?)
            print_error "unrecognized option -- '$OPTARG'"
            exit 1
            ;;
    esac
done

if [[ ! -e "$OUTPUT_DIR" ]] ; then
    printf '%s\n' "${SCRIPT_NAME}: PATH is not exist." 1>&2
    exit 1
fi

if [[ -d "$OUTPUT_DIR" ]] ; then
    printf '%s\n' "${SCRIPT_NAME}: the same directory is already exist." 1>&2
    exit 1
fi

mkdir "$OUTPUT_DIR"

