#!/bin/bash

readonly SCRIPT_NAME=${0##*/}
readonly VERSION=1.0.0

print_help()
{
    cat << END
Test version
END
}

print_version()
{
    cat << END
$SCRIPT_NAME version $VERSION
END
}

print_error()
{
    cat << END 1>&2
$SCRIPT_NAME: $1
Try -h option for more information
END
}

SCRIPT_DIR=$(cd $(dirname $0); pwd)
OUTPUT_DIR="./SSERAFIM"
SET_SRA_LIST_PATH=false

while getopts :o:hV option
do
    case "$option" in
        o)
            OUTPUT_DIR=$OPTARG
            ;;
        s)
            SRA_LIST_PATH=$OPTARG
            SET_SRA_LIST_PATH=true
            ;;
        h)
            print_help
            exit 0
            ;;
        V)
            print_version
            exit 0
            ;;
        :)
            print_error "option requires an argument -- '$OPTARG'"
            exit 1
            ;;
        \?)
            print_error "unrecognized option -- '$OPTARG'"
            exit 1
            ;;
    esac
done

if [ "${SET_SRA_LIST_PATH=true}" != true ]; then
    printf '%s\n' "${SCRIPT_NAME}: need more option" 1>&2
    print_help
    exit 1
fi

if [[ -d "$OUTPUT_DIR" ]] ; then
    printf '%s\n' "${SCRIPT_NAME}: the same directory is already exist." 1>&2
    exit 1
fi
#better mkdir -p ?

mkdir "$OUTPUT_DIR"

bash $SCRIPT_DIR/subscript/sra_download.sh $OUTPUT_DIR $SRA_LIST_PATH